### ISSUE TITLE
C dependeny is not working

### ISSUE THREAD

**Issue by chrisken10** [massivemadness/Brackeys-IDE#21]
*Please consider making a Pull Request if you are capable of doing so.*

**Describe the bug**
After including the dependency `com.brackeys.ui:language-c:1.0.0` and syncing the code. When I try to run the app it gives the below mentioned error.

```Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find Brackeys-IDE.languages:language-base:unspecified.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/Brackeys-IDE/languages/language-base/unspecified/language-base-unspecified.pom
       - https://jcenter.bintray.com/Brackeys-IDE/languages/language-base/unspecified/language-base-unspecified.pom
       - https://jitpack.io/Brackeys-IDE/languages/language-base/unspecified/language-base-unspecified.pom
     Required by:
         project :app > com.brackeys.ui:language-c:1.0.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html 
```

And I also tried with latest dependency `com.brackeys.ui:language-c:1.0.1` but it is not getting resolved.

**To Reproduce**
1. Include the dependency of C Language.
2. Sync Files
3. Click Run button to build project, error will occur while build is running.

**Comment by massivemadness** [comment]
Hi, I'm sorry for the delay, it looks like a problem with maven's pom file... I'll fix it within a few days, thanks for reporting

**Comment by massivemadness** [comment]
I just realized that it's not even included in jcenter repository... 🤦 I sent the request, now it should be fixed within an hour or so.

**Comment by massivemadness** [comment]
Fixed
<img width="1100" alt="Снимок экрана 2020-12-10 в 19 40 23" src="https://user-images.githubusercontent.com/7825871/101801607-96811900-3b1f-11eb-9457-48ebc38289f6.png">

**Comment by chrisken10** [comment]
@massivemadness Thanks
