### ISSUE TITLE
Markdown is not working

### ISSUE THREAD

**Issue by devfoFikiCar** [massivemadness/Brackeys-IDE#25]
When using markdown language it does not highlight anything, or for that matter do anything, is this expected behaviour or is an error?

**Comment by massivemadness** [comment]
Looks like everything is fine. Can you show me your code?

![photo_2020-12-17_21-55-36](https://user-images.githubusercontent.com/7825871/102531230-0741ab80-40b3-11eb-8b9d-9798efd49b0d.jpg)

**Comment by devfoFikiCar** [comment]
Here is my code
![Screen Shot 2020-12-18 at 8 31 18 AM](https://user-images.githubusercontent.com/46137969/102587493-35070e80-410c-11eb-9fe2-81260a826a4f.png)

Here is issue
![Screen Shot 2020-12-18 at 8 36 03 AM](https://user-images.githubusercontent.com/46137969/102587504-3a645900-410c-11eb-9ef9-47cb9747e39e.png)

Also no new line number, it is wierd since I have another in different activity for java and python and it works without an issue

**Comment by massivemadness** [comment]
@devfoFikiCar You have to call `editor.setTextContent("string")` method at least once before you can start using it

**Comment by devfoFikiCar** [comment]
@massivemadness  I do set it on button click

**Comment by devfoFikiCar** [comment]
Do I need to constantly update it or is just one button click enought

**Comment by devfoFikiCar** [comment]
@massivemadness  Aha thanks for the help, I had an error with thay button, it works fine now.
