### ISSUE TITLE
Round corners

### ISSUE THREAD

**Issue by devfoFikiCar** [massivemadness/Brackeys-IDE#26]
It would be great to allow round corners, I tried to make them round, as I would with regular edittext, but it does not work.

**Comment by massivemadness** [comment]
This can be achieved by wrapping `TextProcessor` in `CardView`

```xml
<MaterialCardView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:cardCornerRadius="4dp">

    <com.brackeys.ui.widget.TextProcessor ... />

</MaterialCardView>
```

![Screenshot_2020-12-31-15-04-34-616_com blacksquircle template](https://user-images.githubusercontent.com/7825871/103409922-095b3e00-4b7a-11eb-82b7-936e9d170d73.png)
