### ISSUE TITLE
Auto save files

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [massivemadness/Brackeys-IDE#28]
*Please consider making a Pull Request if you are capable of doing so.*

**Is your feature request related to a problem? Please describe.**
What makes me frustrated is that every time I finish my code, I have to save my files myself. Sometimes I forget to, and next time I open this app, seeing my unsaved code, I feel upset for having to write the code again.

**Describe the solution you'd like**
Automatically save files once in a period of time, e.g. 1min. The time should be adjustable.

**Describe alternatives you've considered**
Save files myself. But it's inconvenient.

**Additional context**
None.

**Comment by massivemadness** [comment]
I think it would be even better if the auto save could work simultaneously with file caching

**Comment by CodeCrazy-ywt** [comment]
OK, I see.

**Comment by CodeCrazy-ywt** [comment]
> @CodeCrazy-ywt I think it would be even better if the auto save could work simultaneously with file caching
> 
> **UPD:** `«I feel upset for having to write the code again.»` sounds like a new issue, because when you exit app it automatically saves all changes in cache, and restores it on the next launch

But there's another worry: even though my changes are cached, when I open files in other apps, what I see is still my unsaved code.

**Comment by massivemadness** [comment]
6ceaca92aaac4b6019faa11f6edf9cae7f2d2177
