### ISSUE TITLE
Text Auto Zoom Out

### ISSUE THREAD

**Issue by chrisken10** [massivemadness/Brackeys-IDE#30]
**Describe the bug**
When I open an activity with some text in the code editor. Text is somewhat zoomed in by default. Then I have to manually zoom it out.
How do I automatically zoom out to max range whenever I open the activity? (i.e. default should be completely zoomed out text)

**Comment by massivemadness** [comment]
You can change the default text size in the Settings -> Editor -> Editor font size

Is that what you're looking for?

**Comment by chrisken10** [comment]
@massivemadness ok, it works. Thanks.
