### ISSUE TITLE
Color error

### ISSUE THREAD

**Issue by devfoFikiCar** [massivemadness/Brackeys-IDE#37]
When you set text content it does not show color till user updates code, is there any way to avoid what and display color right away?

**Comment by massivemadness** [comment]
@devfoFikiCar I need more info to investigate that. Can you show me your code? 

I guess the problem is not in a library, because the main app works fine

**Comment by devfoFikiCar** [comment]
`tpCode.setTextContent(bundle.getString("code"));
         System.out.println(bundle.getString("code"));
         tpCode.setLanguage(new PythonLanguage());
         tpCode.setColorScheme(EditorTheme.INSTANCE.getMONOKAI()); `

**Comment by massivemadness** [comment]
@devfoFikiCar You have to set the language first
