### ISSUE TITLE
i need java version of this codeeditor

### ISSUE THREAD

**Issue by RohitVermaOP** [massivemadness/Brackeys-IDE#42]
Please make java version

**Comment by massivemadness** [comment]
I prefer to use Kotlin as it simplifies the development process a lot and it's fully compatible with Java, so you can use the code editor library even in Java projects.

**Comment by RohitVermaOP** [comment]
Any java doc.?

**Comment by massivemadness** [comment]
https://kotlinlang.org/docs/java-to-kotlin-interop.html
