### ISSUE TITLE
Add Brackeys to "Open with" dialogue

### ISSUE THREAD

**Issue by alexanderadam** [massivemadness/Brackeys-IDE#46]
**Describe the solution you'd like**

[Brackeys](https://f-droid.org/packages/com.brackeys.ui/) should appear in the "Open with" dialogue.
I tried to open a file and I also tried to open a project directory but Brackeys wasn't in the list of applications of either of them.

**Additional context**

I just found Brackeys via F-Droid and wanted to try it. Thus I wanted to open a Ruby file but Brackeys isn't in the list of applications:

![termux-open projects/website/config.rb   Open with "Krita" "Termux"](https://user-images.githubusercontent.com/372620/111525099-7df74f00-875d-11eb-86e5-9b550aac54c1.png)

So you probably would [have to add text files and source code files as association to the `AndroidManifest.xml`](https://richardleggett.com/blog/2013/01/26/registering_for_file_types_in_android/).

Since in this case I wanted to open a Ruby file, this would need at least the MIME type `text/x-ruby` but I guess adding something like `<data android:mimeType="text/*" />` would solve this generically for all text file.

_If_ Brackeys should be suggested for _any_ file type, you could probably also simply use `<data android:mimeType="*/*" />` in the manifest and then you could even still match for file extensions with something like `<data android:pathPattern=".*\\.rb" />` (I don't think that matching a file extension would be necessary though).

And for opening directories, you probably would have to use the [`DocumentsContract.Document.MIME_TYPE_DIR
`](https://developer.android.com/reference/android/provider/DocumentsContract.Document#MIME_TYPE_DIR) (`vnd.android.document/directory` and for compatibility reasons maybe also `inode/directory`).

**PS:** Thank you so much for Brackeys. So far it looks great! 🙏 
**PPS:** I'm not an Android developer so I don't know whether any of what I wrote makes any sense 😉

**Comment by massivemadness** [comment]
@alexanderadam f3f9b7cfd17900ddbc96e621f50cb3afc924f5f4
